export default {
	CHANGE_PASSWORD_FORM_VALDIDATION: 'CHANGE_PASSWORD_FORM_VALDIDATION',
	CHANGE_PASSWORD_RESET_VALIDATION: 'CHANGE_PASSWORD_RESET_VALIDATION',
	CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
	CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
	CHANGE_PASSWORD_FAILURE_PASSWORD: 'CHANGE_PASSWORD_FAILURE_PASSWORD',
	CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE'
}