version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i npm@latest -g
      - npm i serverless@latest -g
      # - pip install --upgrade pip
      # - pip install --upgrade awscli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # - cd barelinks-API-service
      # - sls deploy --stage $STAGE
      - aws cloudfront create-invalidation --distribution-id E2WAL8O6O28TIF --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: build
