
export default {
	LOGIN_FORM_VALDIDATION: 'LOGIN_FORM_VALDIDATION',
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE_PASSWORD: 'LOGIN_FAILURE_PASSWORD',
	LOGIN_FAILURE_NOT_CONFIRMED: 'LOGIN_FAILURE_NOT_CONFIRMED',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	LOGIN_RESET_VALIDATION: 'LOGIN_RESET_VALIDATION',
	LOGOUT: 'LOGOUT'
};