
export default {
	SIGNUP_FORM_VALDIDATION: 'SIGNUP_FORM_VALDIDATION',
	SIGNUP_REQUEST: 'SIGNUP_REQUEST',
	SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
	SIGNUP_FAILURE: 'SIGNUP_FAILURE',
	SIGNUP_RESET_VALIDATION: 'SIGNUP_RESET_VALIDATION'
};