service: barelinks-api-service
# app and org for use with dashboard.serverless.com
# app: barelinks
org: tdehollain

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    # BARELINKS_TABLE: ${self:app}-${self:provider.stage}
    BARELINKS_TABLE: barelinks-${self:provider.stage}
    STAGE: ${self:provider.stage}

  # IAM statements
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt': ['BarelinksTable', 'Arn']

functions:
  getLinks:
    handler: functions/getLinks.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /link
          method: GET
          cors: true
  putLink:
    handler: functions/putLink.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /link
          method: PUT
          cors: true
  deleteLink:
    handler: functions/deleteLink.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /link
          method: DELETE
          cors: true
  getLinksByTag:
    handler: functions/getLinksByTag.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /linksbytag
          method: GET
          cors: true
  getLinksBySearchTerm:
    handler: functions/getLinksBySearchTerm.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /linksbysearchterm
          method: GET
          cors: true
  getTags:
    handler: functions/getTags.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /tags
          method: GET
          cors: true
  updateLink:
    handler: functions/updateLink.handler
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: /link/tag
          method: POST
          cors: true

resources:
  Resources:
    BarelinksTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: linkId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: linkId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.BARELINKS_TABLE}
