export default {
	RESET_PASSWORD_FORM_VALDIDATION: 'RESET_PASSWORD_FORM_VALDIDATION',
	RESET_PASSWORD_RESET_VALIDATION: 'RESET_PASSWORD_RESET_VALIDATION',
	RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
	RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
	RESET_PASSWORD_FAILURE_EXPIRED_CODE: 'RESET_PASSWORD_FAILURE_EXPIRED_CODE',
	RESET_PASSWORD_FAILURE_PASSWORD: 'RESET_PASSWORD_FAILURE_PASSWORD',
	RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE'
}